# Generated by Django 4.2.28 on 2026-02-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypoll',
            name='hard_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklypoll',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklypoll',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklypoll',
            name='locked_by_max',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklypoll',
            name='max_players',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='weeklypoll',
            name='min_players',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
