# Generated by Django 4.2.28 on 2026-02-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_evaluations_received', to='players.player')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_evaluations_given', to='players.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='evaluations.evaluationround')),
            ],
            options={
                'db_table': 'evaluations_assignment',
                'unique_together': {('round', 'evaluator', 'evaluated')},
            },
        ),
    ]
