# Generated by Django 4.2.28 on 2026-02-06 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'players_organization',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'players_player',
                'unique_together': {('organization', 'pseudo')},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('team_a_goals', models.PositiveIntegerField(default=0)),
                ('team_b_goals', models.PositiveIntegerField(default=0)),
                ('distribution_code', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_sent_to_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_received', to='players.player')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='players.organization')),
            ],
            options={
                'db_table': 'players_game',
                'ordering': ['-game_date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('A', 'Team A'), ('B', 'Team B')], max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='players.game')),
                ('players', models.ManyToManyField(blank=True, related_name='team_memberships', to='players.player')),
            ],
            options={
                'db_table': 'players_team',
                'unique_together': {('game', 'side')},
            },
        ),
        migrations.CreateModel(
            name='PhysicalConditionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_reports', to='players.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_reports', to='players.player')),
            ],
            options={
                'db_table': 'players_physical_condition_report',
                'unique_together': {('player', 'game')},
            },
        ),
    ]
